name = "real-personal"
compatibility_date = "2024-12-01"

# After creating the database, replace the database_id below:
#   npx wrangler d1 create climbing-logs
[[d1_databases]]
binding = "DB"
database_name = "climbing-logs"
database_id = "570ba0bf-31aa-4dcd-aa43-221f4ec4c8d2"